### ISSUE TITLE
bma180 two complement is int size dependent.

### ISSUE THREAD

**Issue by miky2k** [johnmccombs/arduino-libraries#6]
I try to compile your code for esp8266  that is a 32bit cpu  and i notice that you assume 16bit int size,
better leave to compiler these work!

here a possible solution
if (x&0x2000){
    	x= x-0b11111111111111-1;  
    	//x|=0xc000; // set full 2 complement for neg values
    }

**Comment by johnmccombs** [comment]
From the readme for this repo "Snapshot of my Arduino libraries folder. I'd recommend you get the libraries from the original sources, as these are not necessarily the most recent versions...."

**Comment by miky2k** [comment]
No copyright or licence in files sorry.

Are fabio varesano libraries ?

**Comment by johnmccombs** [comment]
I'd suggest you take a look at the adafruit bma180 driver - likely o the most recently worked on an compatible with a wide range of hardware.

**Comment by miky2k** [comment]
Does not exist an adafruit BMA180  board, only sparkfun with an arduino example code(not a library).

BMA180 from my search is only used in freeIMU 3.5 (but soon changed with better6050), but if you have different informations please  leave a link and update your library.
You and Varesano (RIP!) github are the first results seraching bmA180 (not bmP180!)).

**Comment by johnmccombs** [comment]
sorry, i thought you were asking about a bma180 
https://www.adafruit.com/product/1603
https://learn.adafruit.com/bmp085/downloads
